### ISSUE TITLE
document available: PDP-11 Processor Handbook 1981

### ISSUE THREAD

**Issue by bjorend** [LegalizeAdulthood/manx#113]
https://manx-docs.org/details.php/1,8192
says no copies are known to be online.
It's available from http://bitsavers.org/pdf/dec/pdp11/handbooks/PDP-11_Processor_Handbook_1981.pdf
Thanks!
--Bjoren Davis

**Comment by LegalizeAdulthood** [comment]
Added
https://manx-docs.org/details.php/1,8192
