### ISSUE TITLE
MP-01394 DEC PC350 Field Maintenance Print Set now available on bitsavers.org

### ISSUE THREAD

**Issue by bjorend** [LegalizeAdulthood/manx#116]
The MP-01394 Field Maintenance Print Set for the DEC PC350 is now available on bitsavers.org: http://bitsavers.org/pdf/dec/pdp11/pro3xx/MP-01394_PC350_Field_Maintenance_Print_Set_.pdf

**Comment by LegalizeAdulthood** [comment]
Added
https://manx-docs.org/details.php/1,5533
