### ISSUE TITLE
The RK611 and KK11-A document is indeed available from bitsavers

### ISSUE THREAD

**Issue by MattisLind** [LegalizeAdulthood/manx#118]
http://bitsavers.trailing-edge.com/pdf/dec/unibus/MP00105_RK611_schem_Aug77.pdf

http://www.bitsavers.org/pdf/dec/pdp11/1134/MP00574_KK11-A_Aug78.pdf

Listed as not online at manx-docs.

**Comment by LegalizeAdulthood** [comment]
Added
https://manx-docs.org/details.php/1,4081
https://manx-docs.org/details.php/1,11748
