### ISSUE TITLE
Measure code coverage from tests

### ISSUE THREAD

**Issue by LegalizeAdulthood** [LegalizeAdulthood/manx#12]
Use [php-coveralls](https://github.com/php-coveralls/php-coveralls/) to measure coverage in travis

**Comment by LegalizeAdulthood** [comment]
Use [coveralls.io](https://docs.coveralls.io/php) for automated coverage reports

**Comment by smrhoney** [comment]
I submitted a pull request for this issue.

**Comment by LegalizeAdulthood** [comment]
Now just need to add a coveralls badge to the README.md to complete this issue.  @smrhoney  Thanks for the pull request!

**Comment by LegalizeAdulthood** [comment]
Badge added to readme on master
