### ISSUE TITLE
Broken URL for "creating a work item for the Data component"

### ISSUE THREAD

**Issue by pbirkel** [LegalizeAdulthood/manx#127]
The URL http://manx.codeplex.com/WorkItem/Create is currently failing.

As this is an important, if not the primary, mechanism for adding new content, it should be re-established with some urgency.

Thank you.

**Comment by LegalizeAdulthood** [comment]
This is a duplicate of #89 which has been fixed, but not yet deployed.  The next update is planned to be deployed sometime before VCFmw 2022.

**Comment by pbirkel** [comment]
Thank you.  An issue since 2019!  Looking forward to seeing the capability re-established so that I can understand its relevance to my use-scenarios.  Looks like VCFMW is September 10-11 this year.

**Comment by LegalizeAdulthood** [comment]
It's not anything more than just a link to this repository's github "create an issue" page.   There's no automation associated with it.

**Comment by pbirkel** [comment]
Ah.  I thought that there might be a self-serve interface to collect metadata and identify the document URL.

**Comment by LegalizeAdulthood** [comment]
That's a good idea for a feature though, see #129.

**Comment by LegalizeAdulthood** [comment]
For now I've manually edited the deployed site files to fix the links until the next version is deployed.
