### ISSUE TITLE
COBOL 68 manual online.

### ISSUE THREAD

**Issue by LTepliakov** [LegalizeAdulthood/manx#140]
Hello team!
RE your comment at https://manx-docs.org/details.php/1,12596

Here I found COBOL 68 language manual:
https://www.livingcomputers.org/UI/UserDocs/Tops-10-v7-04/6_COBOL-68_Language_Manual.pdf

**Comment by LegalizeAdulthood** [comment]
Thanks, I wonder how long that will stay online?  LCM is being dismantled.

**Comment by LegalizeAdulthood** [comment]
That online copy is revision B part number AA-5057B-TK which manx already knows about here:
https://manx-docs.org/details.php/1,4109
