### ISSUE TITLE
HP 700 Series Terminals User Manuals

### ISSUE THREAD

**Issue by kd8drx** [LegalizeAdulthood/manx#141]
Heya!

Per the Manx site, there are no known copies of the [HP 700/96 and HP 700/96ES, HP 700/98 and HP 700/98ES User's Manual](https://manx-docs.org/details.php/7,10070).

However, a copy of this document is available on the Internet Archive at https://archive.org/details/bitsavers_hpterminal50717009698TerminalsUsersManual595950711_3639380/mode/2up

**Comment by LegalizeAdulthood** [comment]
Fixed: https://manx-docs.org/details.php/7,22076

Thanks.
